depends:
    - test-runner
    - serializer
    - serial-datagram
    - cmp

source:
    - can_frame_cmp.c
    - serial_can_bridge.c

tests:
    - tests/can_frame_tests.cpp
    - tests/bridge_test.cpp
    - mock/can_interface_mock.c
